import = ["/home/ds/.config/alacritty/tokyonight/tokyonight_night.toml"]

[cursor]
style = "beam"

[env]
WINIT_X11_SCALE_FACTOR = "1"

[font]
size = 14

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "SemiBold"

[window.padding]
# dynamic_padding = true
x = 16
y = 16

[window]
opacity = 0.75
